### ISSUE TITLE
Login process with 2fa

### ISSUE THREAD

**Issue by Scelewyn** [znichola/ft_transcendence#38]
**How to inform the frontend that tfa is enabled ?**
_As of now, logging in returns a JSON object with the user login42, and 2fa status (true or false). If it is true, then the user should be asked for his Authenticator code, then a POST request to /tfa/{username}/login should be sent, with a body containing the code as tfaCode (6 characters string, no space)_

**What to provide to the frontend after a successful login ?**
_I currently send back the login42 of the logged in user. Please let me know if this work for you, or if you want me to return more/different data_

**Comment by znichola** [comment]
I think this is enough for the moment, I'm working on the redirection cycle that needs to happen to get to the user to the page with the code input. But I'm still not sure what this is supposed to look like, can you give me a flow diagram?

Spesifically:
1 - what needs to happen to set up the tfa
2 - what happens when a user with tfa tries to log in

**Comment by znichola** [comment]
if `tfa:true`
we redirect to this page,
then on button click nothing happens for now but I guess, it's then that the signin is done? 

<img width="331" alt="Screen Shot 2023-10-14 at 4 40 49 PM" src="https://github.com/znichola/ft_transcendence/assets/12100623/66c9de01-58dd-40b9-8557-d47b0f11113e">

**Comment by Scelewyn** [comment]
Yes it's perfect, just tried to login now and I get to this button
All that's needed when you click this submit button is to send a POST request to /tfa/{username}/login, with the code in the body like this : tfaCode : {code}

I throw an Unauthorized Exception when the code is invalid
